// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

// Package pb defines MinBFT protocol messages in Protobuf format.

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Message represents arbitrary protocol message.
type Message struct {
	// Types that are valid to be assigned to Typed:
	//	*Message_Request
	//	*Message_Reply
	//	*Message_Prepare
	//	*Message_Commit
	//	*Message_ReqViewChange
	//	*Message_ViewChange
	Typed                isMessage_Typed `protobuf_oneof:"typed"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Typed interface {
	isMessage_Typed()
}

type Message_Request struct {
	Request *Request `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type Message_Reply struct {
	Reply *Reply `protobuf:"bytes,2,opt,name=reply,proto3,oneof"`
}

type Message_Prepare struct {
	Prepare *Prepare `protobuf:"bytes,3,opt,name=prepare,proto3,oneof"`
}

type Message_Commit struct {
	Commit *Commit `protobuf:"bytes,4,opt,name=commit,proto3,oneof"`
}

type Message_ReqViewChange struct {
	ReqViewChange *ReqViewChange `protobuf:"bytes,5,opt,name=req_view_change,json=reqViewChange,proto3,oneof"`
}

type Message_ViewChange struct {
	ViewChange *ViewChange `protobuf:"bytes,6,opt,name=view_change,json=viewChange,proto3,oneof"`
}

func (*Message_Request) isMessage_Typed() {}

func (*Message_Reply) isMessage_Typed() {}

func (*Message_Prepare) isMessage_Typed() {}

func (*Message_Commit) isMessage_Typed() {}

func (*Message_ReqViewChange) isMessage_Typed() {}

func (*Message_ViewChange) isMessage_Typed() {}

func (m *Message) GetTyped() isMessage_Typed {
	if m != nil {
		return m.Typed
	}
	return nil
}

func (m *Message) GetRequest() *Request {
	if x, ok := m.GetTyped().(*Message_Request); ok {
		return x.Request
	}
	return nil
}

func (m *Message) GetReply() *Reply {
	if x, ok := m.GetTyped().(*Message_Reply); ok {
		return x.Reply
	}
	return nil
}

func (m *Message) GetPrepare() *Prepare {
	if x, ok := m.GetTyped().(*Message_Prepare); ok {
		return x.Prepare
	}
	return nil
}

func (m *Message) GetCommit() *Commit {
	if x, ok := m.GetTyped().(*Message_Commit); ok {
		return x.Commit
	}
	return nil
}

func (m *Message) GetReqViewChange() *ReqViewChange {
	if x, ok := m.GetTyped().(*Message_ReqViewChange); ok {
		return x.ReqViewChange
	}
	return nil
}

func (m *Message) GetViewChange() *ViewChange {
	if x, ok := m.GetTyped().(*Message_ViewChange); ok {
		return x.ViewChange
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_Request)(nil),
		(*Message_Reply)(nil),
		(*Message_Prepare)(nil),
		(*Message_Commit)(nil),
		(*Message_ReqViewChange)(nil),
		(*Message_ViewChange)(nil),
	}
}

// Request represents REQUEST message.
type Request struct {
	// Client identifier
	ClientId uint32 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Request identifier (timestamp / sequence number)
	Seq uint64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// Operation to execute on replicated state machine
	Operation []byte `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	// Client's signature
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetClientId() uint32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *Request) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Request) GetOperation() []byte {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *Request) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Reply represents REPLY message.
type Reply struct {
	// Replica identifier
	ReplicaId uint32 `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	// Client identifier
	ClientId uint32 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Request identifier
	Seq uint64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	// Result of requested operation execution
	Result []byte `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	// Replica's signature
	Signature            []byte   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetReplicaId() uint32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *Reply) GetClientId() uint32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *Reply) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Reply) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Reply) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Prepare represents PREPARE message.
type Prepare struct {
	// Replica identifier
	ReplicaId uint32 `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	// View number
	View uint64 `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	// Client's REQUEST
	Request *Request `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	// Replica's UI
	Ui                   []byte   `protobuf:"bytes,4,opt,name=ui,proto3" json:"ui,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prepare) Reset()         { *m = Prepare{} }
func (m *Prepare) String() string { return proto.CompactTextString(m) }
func (*Prepare) ProtoMessage()    {}
func (*Prepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *Prepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prepare.Unmarshal(m, b)
}
func (m *Prepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prepare.Marshal(b, m, deterministic)
}
func (m *Prepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prepare.Merge(m, src)
}
func (m *Prepare) XXX_Size() int {
	return xxx_messageInfo_Prepare.Size(m)
}
func (m *Prepare) XXX_DiscardUnknown() {
	xxx_messageInfo_Prepare.DiscardUnknown(m)
}

var xxx_messageInfo_Prepare proto.InternalMessageInfo

func (m *Prepare) GetReplicaId() uint32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *Prepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Prepare) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Prepare) GetUi() []byte {
	if m != nil {
		return m.Ui
	}
	return nil
}

// Commit represents COMMIT message.
type Commit struct {
	// Replica identifier
	ReplicaId uint32 `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	// Primary's PREPARE
	Prepare *Prepare `protobuf:"bytes,2,opt,name=prepare,proto3" json:"prepare,omitempty"`
	// Replica's UI
	Ui                   []byte   `protobuf:"bytes,3,opt,name=ui,proto3" json:"ui,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetReplicaId() uint32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *Commit) GetPrepare() *Prepare {
	if m != nil {
		return m.Prepare
	}
	return nil
}

func (m *Commit) GetUi() []byte {
	if m != nil {
		return m.Ui
	}
	return nil
}

// ReqViewChange represents REQ-VIEW-CHANGE message.
type ReqViewChange struct {
	// Replica identifier
	ReplicaId uint32 `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	// Current view number
	View uint64 `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	// New view number
	RequestedView uint64 `protobuf:"varint,3,opt,name=requested_view,json=requestedView,proto3" json:"requested_view,omitempty"`
	// Replica's signature
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqViewChange) Reset()         { *m = ReqViewChange{} }
func (m *ReqViewChange) String() string { return proto.CompactTextString(m) }
func (*ReqViewChange) ProtoMessage()    {}
func (*ReqViewChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}

func (m *ReqViewChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqViewChange.Unmarshal(m, b)
}
func (m *ReqViewChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqViewChange.Marshal(b, m, deterministic)
}
func (m *ReqViewChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqViewChange.Merge(m, src)
}
func (m *ReqViewChange) XXX_Size() int {
	return xxx_messageInfo_ReqViewChange.Size(m)
}
func (m *ReqViewChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqViewChange.DiscardUnknown(m)
}

var xxx_messageInfo_ReqViewChange proto.InternalMessageInfo

func (m *ReqViewChange) GetReplicaId() uint32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *ReqViewChange) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *ReqViewChange) GetRequestedView() uint64 {
	if m != nil {
		return m.RequestedView
	}
	return 0
}

func (m *ReqViewChange) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// ViewChange represents VIEW-CHANGE message.
type ViewChange struct {
	// Replica identifier
	ReplicaId uint32 `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	// Other Replicas REQ-VIEW-CHANGE
	ReqViewChange *ReqViewChange `protobuf:"bytes,2,opt,name=req_view_change,json=reqViewChange,proto3" json:"req_view_change,omitempty"`
	// New View
	NewView uint64 `protobuf:"varint,3,opt,name=new_view,json=newView,proto3" json:"new_view,omitempty"`
	// Replica's signature
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewChange) Reset()         { *m = ViewChange{} }
func (m *ViewChange) String() string { return proto.CompactTextString(m) }
func (*ViewChange) ProtoMessage()    {}
func (*ViewChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{6}
}

func (m *ViewChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewChange.Unmarshal(m, b)
}
func (m *ViewChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewChange.Marshal(b, m, deterministic)
}
func (m *ViewChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewChange.Merge(m, src)
}
func (m *ViewChange) XXX_Size() int {
	return xxx_messageInfo_ViewChange.Size(m)
}
func (m *ViewChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewChange.DiscardUnknown(m)
}

var xxx_messageInfo_ViewChange proto.InternalMessageInfo

func (m *ViewChange) GetReplicaId() uint32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *ViewChange) GetReqViewChange() *ReqViewChange {
	if m != nil {
		return m.ReqViewChange
	}
	return nil
}

func (m *ViewChange) GetNewView() uint64 {
	if m != nil {
		return m.NewView
	}
	return 0
}

func (m *ViewChange) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Reply)(nil), "pb.Reply")
	proto.RegisterType((*Prepare)(nil), "pb.Prepare")
	proto.RegisterType((*Commit)(nil), "pb.Commit")
	proto.RegisterType((*ReqViewChange)(nil), "pb.ReqViewChange")
	proto.RegisterType((*ViewChange)(nil), "pb.ViewChange")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x6d, 0x9c, 0x26, 0xd9, 0x4e, 0xb7, 0x05, 0x7c, 0x40, 0x41, 0x80, 0x04, 0x15, 0x2b, 0x38,
	0x55, 0x02, 0x4e, 0x88, 0x1b, 0x7b, 0xe9, 0x1e, 0x90, 0x90, 0x0f, 0x1c, 0xa9, 0xd2, 0x66, 0x54,
	0x2c, 0xb5, 0x89, 0x6b, 0x3b, 0x1b, 0xf5, 0x17, 0x70, 0xe0, 0x37, 0x20, 0xfe, 0x2a, 0xf2, 0x07,
	0x75, 0xb3, 0x05, 0x05, 0x71, 0x8b, 0xdf, 0xcc, 0x3c, 0x3f, 0x3f, 0x3f, 0x07, 0xa6, 0x3b, 0x54,
	0xaa, 0xd8, 0xa0, 0x9a, 0x0b, 0x59, 0xeb, 0x9a, 0x12, 0xb1, 0x9a, 0xfd, 0x20, 0x90, 0x7d, 0x74,
	0x30, 0x7d, 0x09, 0x99, 0xc4, 0x7d, 0x83, 0x4a, 0xe7, 0xd1, 0xb3, 0xe8, 0xd5, 0xf8, 0xcd, 0x78,
	0x2e, 0x56, 0x73, 0xe6, 0xa0, 0xc5, 0x80, 0xfd, 0xae, 0xd2, 0xe7, 0x90, 0x48, 0x14, 0xdb, 0x43,
	0x4e, 0x6c, 0xdb, 0xc8, 0xb5, 0x89, 0xed, 0x61, 0x31, 0x60, 0xae, 0x62, 0xb8, 0x84, 0x44, 0x51,
	0x48, 0xcc, 0xe3, 0xc0, 0xf5, 0xc9, 0x41, 0x86, 0xcb, 0x57, 0xe9, 0x0b, 0x48, 0xd7, 0xf5, 0x6e,
	0xc7, 0x75, 0x3e, 0xb4, 0x7d, 0x60, 0xfa, 0xae, 0x2d, 0xb2, 0x18, 0x30, 0x5f, 0xa3, 0xef, 0xe1,
	0x9e, 0xc4, 0xfd, 0xf2, 0x96, 0x63, 0xbb, 0x5c, 0x7f, 0x2d, 0xaa, 0x0d, 0xe6, 0x89, 0x6d, 0x7f,
	0xe0, 0x25, 0x7e, 0xe6, 0xd8, 0x5e, 0xdb, 0xc2, 0x62, 0xc0, 0x26, 0xf2, 0x14, 0xa0, 0xaf, 0x61,
	0x7c, 0x3a, 0x98, 0xda, 0xc1, 0xa9, 0x19, 0xec, 0x4c, 0xc1, 0xed, 0x71, 0xf5, 0x21, 0x83, 0x44,
	0x1f, 0x04, 0x96, 0x33, 0x0d, 0x99, 0x37, 0x80, 0x3e, 0x86, 0xd1, 0x7a, 0xcb, 0xb1, 0xd2, 0x4b,
	0x5e, 0x5a, 0x83, 0x26, 0xec, 0xc2, 0x01, 0x37, 0x25, 0xbd, 0x0f, 0xb1, 0xc2, 0xbd, 0x35, 0x64,
	0xc8, 0xcc, 0x27, 0x7d, 0x02, 0xa3, 0x5a, 0xa0, 0x2c, 0x34, 0xaf, 0x2b, 0xeb, 0xc1, 0x25, 0x0b,
	0x80, 0xa9, 0x2a, 0xbe, 0xa9, 0x0a, 0xdd, 0x48, 0xb4, 0x27, 0xbf, 0x64, 0x01, 0x98, 0x7d, 0x8f,
	0x20, 0xb1, 0x86, 0xd2, 0xa7, 0x00, 0xc6, 0x50, 0xbe, 0x2e, 0xc2, 0xae, 0x23, 0x8f, 0xdc, 0x94,
	0x5d, 0x4d, 0xe4, 0xcf, 0x9a, 0xe2, 0xa0, 0xe9, 0x21, 0xa4, 0x12, 0x55, 0xb3, 0xd5, 0x7e, 0x4b,
	0xbf, 0xea, 0xaa, 0x49, 0xee, 0xaa, 0x51, 0x90, 0xf9, 0x8b, 0xeb, 0x93, 0x43, 0x61, 0x68, 0x4c,
	0xf4, 0x36, 0xd8, 0x6f, 0x7a, 0x15, 0x52, 0x15, 0x9f, 0xa5, 0x2a, 0x64, 0x6a, 0x0a, 0xa4, 0xe1,
	0x5e, 0x16, 0x69, 0xf8, 0xec, 0x0b, 0xa4, 0x2e, 0x05, 0x7d, 0x7b, 0x5e, 0x85, 0xa4, 0x91, 0xb3,
	0xa4, 0x85, 0x9c, 0x39, 0xfe, 0xf8, 0xc8, 0xff, 0x2d, 0x82, 0x49, 0x27, 0x37, 0xff, 0x77, 0xb6,
	0xa9, 0xd7, 0x8f, 0xa5, 0x0d, 0xa7, 0x37, 0x7b, 0x72, 0x44, 0x0d, 0x7f, 0xcf, 0x65, 0xff, 0x8c,
	0x00, 0xfe, 0x5d, 0xc6, 0xbb, 0xf3, 0x97, 0x40, 0xfe, 0xf2, 0x12, 0xee, 0xbe, 0x83, 0x47, 0x70,
	0x51, 0x61, 0x7b, 0xaa, 0x33, 0xab, 0xb0, 0xed, 0x57, 0xb8, 0x4a, 0xed, 0xff, 0xe2, 0xed, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xf9, 0x76, 0x8f, 0x41, 0x04, 0x00, 0x00,
}
